### ISSUE TITLE
Duplicate posts when refreshing posts page

### ISSUE THREAD

**Issue by mightypanda-x** [hapramp/1Rramp-Android#128]
#### Expected Behavior
When I refresh my profile page with 2 or more posts, I should see all my posts with no duplicate.

#### Actual Behavior
When refreshing profile page with duplicate posts, I see my first post repeated.

#### Steps to Reproduce
1. Open and login into the app.
2. Go to Profile page (you should have at least 2 posts) alternatively you can search for a profile with multiple posts Ex: @singhpratyush 
3. Pull down on your screen to trigger a refresh as shown in the video.
4. Scroll to the posts area again. You will see that the first post is showing twice and you can't see or access second post anymore.

https://www.youtube.com/watch?v=QD799YXZZgA

* Device : Samsung S8
* System Operating : 8.0.0 Oreo
* App Version: 0.0.12

**Comment by singhpratyush** [comment]
I saw it too. Thanks for reporting :)
