### ISSUE TITLE
[1Ramp] [0.0.13] A blank page appears if discarded while sharing something and nothing works on that page

### ISSUE THREAD

**Issue by sourovafrin** [hapramp/1Rramp-Android#149]
Recordings of the Bug

https://www.youtube.com/watch?v=cL2JDcr0RDs

Device : Huawei y9
Operating System : Android OREO(8.0.0)
App Version : 0.0.13

**Comment by singhpratyush** [comment]
I am getting this issue too. Thanks for reporting @sourovafrin :)
