### ISSUE TITLE
Version 0.0.13 -  "Invite a friend" text can't be discarded after successfully posting in 1ramp

### ISSUE THREAD

**Issue by josephace135** [hapramp/1Rramp-Android#150]
#### Expected behavior
After successfully posting the text for "Invite a friend" thru 1ramp app, the text should be discarded whether the text box was cleared or not.

#### Actual behavior
Upon successfully posting the text meant for "Invite a friend" thru 1ramp app, the text can't be discarded.
	
#### How to reproduce
* Tap "Settings" icon.
* Tap "Invite a friend".
* A pop-up appears and tap "1ramp".
* Then, select any "Community" and then publish.
* After successfully publishing the post, clear the text found in the text box and then tap the "X" icon or simply tap the "X" icon in the top right corner - the issue appears for which the post can't be discarded and still the text appears.

#### Environment
* App/Plugin version: HapRamp-Android v0.0.13
* Device: Samsung Galaxy J2 Prime (SM-G532G/DS)
* Operating system: Android version 6.0.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=EYc2nfe6Cx0

**Comment by singhpratyush** [comment]
I face this bug too. Thanks for reporting @josephace135!
