### ISSUE TITLE
Shows wrong error every time when user tries to power up on 1ramp Android Alpha v0.0.13 revision 2

### ISSUE THREAD

**Issue by sourovafrin** [hapramp/1Rramp-Android#174]
I tried to power up but failed.
It shows wrong error everytime.

https://youtu.be/EH-HaOKHkVY

* Device : Huawei y9
* Operating System : Android OREO(8.0.0)
* App Version : 1ramp Android Alpha v0.0.13 revision 2

**Comment by singhpratyush** [comment]
Thanks for reporting @sourovafrin. Seems like an implementation issue - we'll fix it shortly.
