### ISSUE TITLE
[1ramp Android Alpha v0.0.13 revision 2] When user tries to upload picture on blog posting, the app takes kind of restart

### ISSUE THREAD

**Issue by sourovafrin** [hapramp/1Rramp-Android#175]
I tried to upload image , but every time the app takes kind of restart. On other versions of android below 8.0.0 it can crash.As my one is oreo, it's just restarting.

#### Recording of the bug

https://youtu.be/PqoVzx3VjLg

* Device : Huawei y9
* Operating System : Android OREO(8.0.0)
* App Version : 1ramp Android Alpha v0.0.13 revision 2

**Comment by singhpratyush** [comment]
Thank you @sourovafrin for reporting. This is a critical one, we'll make sure to keep it at high priority.
