### ISSUE TITLE
Links don't load - they try to open an internal address instead

### ISSUE THREAD

**Issue by royachiron** [hapramp/1Rramp-Android#85]
![screenshot_2018-08-14-15-41-56-450_com hapramp](https://user-images.githubusercontent.com/23020420/44092559-73d40cf2-9fd9-11e8-83f5-13643036bff4.png)

The image says it all I think.

Both bbcode and html links yield the same result.

**Comment by singhpratyush** [comment]
Seems like we need link validation before actually accepting it. So `https://www.google.com` would work but `www.google.com` won't. Will that solve the issue?

**Comment by singhpratyush** [comment]
Fixed in 355dff986bc1ef974293644ab9d260b9359e6510.
